default_platform(:ios)

platform :ios do
  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots(scheme: "MarsRovers!Fastlane")
    frame_screenshots(white: true)
  end
end
